"""add_intangible_heritage

Revision ID: 0553331a0ee4
Revises: 1b1cbe154e71
Create Date: 2026-06-01 19:48:47.680197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0553331a0ee4'
down_revision: Union[str, Sequence[str], None] = '1b1cbe154e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intangible_heritage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('community', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('practiced_at', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contribution_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['heritage_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intangible_heritage_id'), 'intangible_heritage', ['id'], unique=False)
    op.create_table('intangible_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intangible_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intangible_id'], ['intangible_heritage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intangible_media_id'), 'intangible_media', ['id'], unique=False)
    op.add_column('contributions', sa.Column('community', sa.String(length=100), nullable=True))
    op.add_column('contributions', sa.Column('language', sa.String(length=100), nullable=True))
    op.add_column('contributions', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('contributions', sa.Column('practiced_at', sa.String(length=255), nullable=True))
    op.add_column('contributions', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('contributions', sa.Column('audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'audio_url')
    op.drop_column('contributions', 'video_url')
    op.drop_column('contributions', 'practiced_at')
    op.drop_column('contributions', 'risk_level')
    op.drop_column('contributions', 'language')
    op.drop_column('contributions', 'community')
    op.drop_index(op.f('ix_intangible_media_id'), table_name='intangible_media')
    op.drop_table('intangible_media')
    op.drop_index(op.f('ix_intangible_heritage_id'), table_name='intangible_heritage')
    op.drop_table('intangible_heritage')
    # ### end Alembic commands ###
