"""Add DateSuggestion and Views Count

Revision ID: 18d27b34ee8d
Revises: d87effd531df
Create Date: 2026-05-29 21:49:19.535904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d27b34ee8d'
down_revision: Union[str, Sequence[str], None] = 'd87effd531df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival_date_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('festival_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('proposed_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposed_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposed_nepali_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_date_suggestions_festival_id'), 'festival_date_suggestions', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festival_date_suggestions_id'), 'festival_date_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_festival_date_suggestions_user_email'), 'festival_date_suggestions', ['user_email'], unique=False)
    op.add_column('festivals', sa.Column('views_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('festivals', 'views_count')
    op.drop_index(op.f('ix_festival_date_suggestions_user_email'), table_name='festival_date_suggestions')
    op.drop_index(op.f('ix_festival_date_suggestions_id'), table_name='festival_date_suggestions')
    op.drop_index(op.f('ix_festival_date_suggestions_festival_id'), table_name='festival_date_suggestions')
    op.drop_table('festival_date_suggestions')
    # ### end Alembic commands ###
