"""Add views_count to heritage_sites

Revision ID: 245f26a57e02
Revises: 9ded3ca8acdc
Create Date: 2026-07-19 21:08:00.737433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245f26a57e02'
down_revision: Union[str, Sequence[str], None] = '9ded3ca8acdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heritage_sites', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heritage_sites', 'views_count')
    # ### end Alembic commands ###
