"""update contributions model

Revision ID: 2c83e14ad018
Revises: f5b0c815b607
Create Date: 2026-04-20 17:52:21.596933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c83e14ad018'
down_revision: Union[str, Sequence[str], None] = 'f5b0c815b607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('significance', sa.Text(), nullable=True))
    op.add_column('contributions', sa.Column('nepali_date', sa.String(), nullable=True))
    op.add_column('contributions', sa.Column('is_annual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'is_annual')
    op.drop_column('contributions', 'nepali_date')
    op.drop_column('contributions', 'significance')
    # ### end Alembic commands ###
