"""add name_np to contribution

Revision ID: 2d4cb669b190
Revises: 8ca87e8ccf3c
Create Date: 2026-06-04 16:18:07.463400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4cb669b190'
down_revision: Union[str, Sequence[str], None] = '8ca87e8ccf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('name_np', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'name_np')
    # ### end Alembic commands ###
