"""add user settings

Revision ID: 39af5558833c
Revises: 2d4cb669b190
Create Date: 2026-06-04 22:15:26.375242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39af5558833c'
down_revision: Union[str, Sequence[str], None] = '2d4cb669b190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('push_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_index(op.f('ix_user_settings_user_email'), 'user_settings', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_email'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
