"""Add contributor_name and contributor_email to contributions table

Revision ID: 3f667b924d55
Revises: 2c83e14ad018
Create Date: 2026-05-21 14:45:18.089838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f667b924d55'
down_revision: Union[str, Sequence[str], None] = '2c83e14ad018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('contributor_name', sa.String(), nullable=True))
    op.add_column('contributions', sa.Column('contributor_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'contributor_email')
    op.drop_column('contributions', 'contributor_name')
    # ### end Alembic commands ###
