"""Add comprehensive user fields including name, profile_photo_url, auth_provider, account_created_at, last_login_at

Revision ID: 4a28f71f2877
Revises: a5780c017403
Create Date: 2026-02-20 22:16:33.253751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a28f71f2877'
down_revision: Union[str, Sequence[str], None] = 'a5780c017403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), server_default='email', nullable=False))
    op.add_column('users', sa.Column('account_created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing users to have default values
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    op.execute("UPDATE users SET account_created_at = NOW() WHERE account_created_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'account_created_at')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
