"""Add firebase_uid and make hashed_password nullable

Revision ID: 74201151d51e
Revises: 202601211400
Create Date: 2026-02-20 19:06:02.015078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74201151d51e'
down_revision: Union[str, Sequence[str], None] = '202601211400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('festivals', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('festivals', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='festivalstatus'),
               nullable=True)
    op.add_column('users', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'firebase_uid')
    op.alter_column('festivals', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='festivalstatus'),
               nullable=False)
    op.alter_column('festivals', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
