"""Add festival interactions

Revision ID: 869806b07071
Revises: 3f667b924d55
Create Date: 2026-05-22 12:09:49.743595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '869806b07071'
down_revision: Union[str, Sequence[str], None] = '3f667b924d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('festival_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'user_email', name='unique_festival_user_reaction')
    )
    op.create_index(op.f('ix_festival_reactions_festival_id'), 'festival_reactions', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festival_reactions_id'), 'festival_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_festival_reactions_user_email'), 'festival_reactions', ['user_email'], unique=False)
    op.create_table('festival_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('festival_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'user_email', name='unique_festival_user_story')
    )
    op.create_index(op.f('ix_festival_stories_festival_id'), 'festival_stories', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festival_stories_id'), 'festival_stories', ['id'], unique=False)
    op.create_index(op.f('ix_festival_stories_user_email'), 'festival_stories', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_festival_stories_user_email'), table_name='festival_stories')
    op.drop_index(op.f('ix_festival_stories_id'), table_name='festival_stories')
    op.drop_index(op.f('ix_festival_stories_festival_id'), table_name='festival_stories')
    op.drop_table('festival_stories')
    op.drop_index(op.f('ix_festival_reactions_user_email'), table_name='festival_reactions')
    op.drop_index(op.f('ix_festival_reactions_id'), table_name='festival_reactions')
    op.drop_index(op.f('ix_festival_reactions_festival_id'), table_name='festival_reactions')
    op.drop_table('festival_reactions')
    # ### end Alembic commands ###
