"""implement comprehensive intangible heritage models

Revision ID: 8ca87e8ccf3c
Revises: 0553331a0ee4
Create Date: 2026-06-04 07:52:21.567071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ca87e8ccf3c'
down_revision: Union[str, Sequence[str], None] = '0553331a0ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intangible_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intangible_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('views_today', sa.Integer(), nullable=True),
    sa.Column('new_favorites', sa.Integer(), nullable=True),
    sa.Column('new_comments', sa.Integer(), nullable=True),
    sa.Column('new_shares', sa.Integer(), nullable=True),
    sa.Column('engagement_score_today', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_engagement_score', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('view_trend', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['intangible_id'], ['intangible_heritage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intangible_analytics_date'), 'intangible_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_intangible_analytics_id'), 'intangible_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_intangible_analytics_intangible_id'), 'intangible_analytics', ['intangible_id'], unique=False)
    op.create_table('intangible_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intangible_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intangible_id'], ['intangible_heritage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['intangible_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intangible_comments_created_at'), 'intangible_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_intangible_comments_id'), 'intangible_comments', ['id'], unique=False)
    op.create_index(op.f('ix_intangible_comments_intangible_id'), 'intangible_comments', ['intangible_id'], unique=False)
    op.create_index(op.f('ix_intangible_comments_parent_comment_id'), 'intangible_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_intangible_comments_user_id'), 'intangible_comments', ['user_id'], unique=False)
    op.create_table('intangible_engagement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intangible_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['intangible_id'], ['intangible_heritage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intangible_engagement_action_type'), 'intangible_engagement', ['action_type'], unique=False)
    op.create_index(op.f('ix_intangible_engagement_created_at'), 'intangible_engagement', ['created_at'], unique=False)
    op.create_index(op.f('ix_intangible_engagement_id'), 'intangible_engagement', ['id'], unique=False)
    op.create_index(op.f('ix_intangible_engagement_intangible_id'), 'intangible_engagement', ['intangible_id'], unique=False)
    op.create_index(op.f('ix_intangible_engagement_user_id'), 'intangible_engagement', ['user_id'], unique=False)
    op.create_table('intangible_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intangible_id', sa.UUID(), nullable=False),
    sa.Column('flagged_by', sa.UUID(), nullable=True),
    sa.Column('flag_reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intangible_id'], ['intangible_heritage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intangible_flags_flag_reason'), 'intangible_flags', ['flag_reason'], unique=False)
    op.create_index(op.f('ix_intangible_flags_flagged_by'), 'intangible_flags', ['flagged_by'], unique=False)
    op.create_index(op.f('ix_intangible_flags_id'), 'intangible_flags', ['id'], unique=False)
    op.create_index(op.f('ix_intangible_flags_intangible_id'), 'intangible_flags', ['intangible_id'], unique=False)
    op.create_index(op.f('ix_intangible_flags_status'), 'intangible_flags', ['status'], unique=False)
    op.add_column('intangible_heritage', sa.Column('name_np', sa.String(length=255), nullable=False))
    op.add_column('intangible_heritage', sa.Column('name_en', sa.String(length=255), nullable=False))
    op.add_column('intangible_heritage', sa.Column('practiced_at_description', sa.String(length=255), nullable=True))
    op.add_column('intangible_heritage', sa.Column('contributor_id', sa.UUID(), nullable=False))
    op.add_column('intangible_heritage', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('intangible_heritage', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('intangible_heritage', sa.Column('rejected_reason', sa.String(length=255), nullable=True))
    op.add_column('intangible_heritage', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('intangible_heritage', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('intangible_heritage', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('intangible_heritage', sa.Column('favorite_count', sa.Integer(), nullable=True))
    op.add_column('intangible_heritage', sa.Column('engagement_score', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('intangible_heritage', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('intangible_heritage', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('intangible_heritage', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('intangible_heritage', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('intangible_heritage', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_intangible_heritage_category'), 'intangible_heritage', ['category'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_community'), 'intangible_heritage', ['community'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_contributor_id'), 'intangible_heritage', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_created_at'), 'intangible_heritage', ['created_at'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_location_id'), 'intangible_heritage', ['location_id'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_risk_level'), 'intangible_heritage', ['risk_level'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_status'), 'intangible_heritage', ['status'], unique=False)
    op.create_index(op.f('ix_intangible_heritage_view_count'), 'intangible_heritage', ['view_count'], unique=False)
    op.drop_constraint(op.f('intangible_heritage_contribution_id_fkey'), 'intangible_heritage', type_='foreignkey')
    op.drop_constraint(op.f('intangible_heritage_location_id_fkey'), 'intangible_heritage', type_='foreignkey')
    op.create_foreign_key(None, 'intangible_heritage', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'intangible_heritage', 'heritage_sites', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'intangible_heritage', 'users', ['contributor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('intangible_heritage', 'is_deleted')
    op.drop_column('intangible_heritage', 'created_by')
    op.drop_column('intangible_heritage', 'name')
    op.drop_column('intangible_heritage', 'practiced_at')
    op.drop_column('intangible_heritage', 'contribution_id')
    op.add_column('intangible_media', sa.Column('file_size_mb', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('intangible_media', sa.Column('mime_type', sa.String(length=50), nullable=False))
    op.add_column('intangible_media', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('intangible_media', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('intangible_media', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('intangible_media', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('intangible_media', sa.Column('processing_status', sa.String(length=20), nullable=True))
    op.add_column('intangible_media', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('intangible_media', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('intangible_media', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.alter_column('intangible_media', 'media_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_index(op.f('ix_intangible_media_intangible_id'), 'intangible_media', ['intangible_id'], unique=False)
    op.create_index(op.f('ix_intangible_media_media_type'), 'intangible_media', ['media_type'], unique=False)
    op.create_index(op.f('ix_intangible_media_processing_status'), 'intangible_media', ['processing_status'], unique=False)
    op.create_index(op.f('ix_intangible_media_uploaded_by'), 'intangible_media', ['uploaded_by'], unique=False)
    op.drop_constraint(op.f('intangible_media_intangible_id_fkey'), 'intangible_media', type_='foreignkey')
    op.create_foreign_key(None, 'intangible_media', 'intangible_heritage', ['intangible_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'intangible_media', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intangible_media', type_='foreignkey')
    op.drop_constraint(None, 'intangible_media', type_='foreignkey')
    op.create_foreign_key(op.f('intangible_media_intangible_id_fkey'), 'intangible_media', 'intangible_heritage', ['intangible_id'], ['id'])
    op.drop_index(op.f('ix_intangible_media_uploaded_by'), table_name='intangible_media')
    op.drop_index(op.f('ix_intangible_media_processing_status'), table_name='intangible_media')
    op.drop_index(op.f('ix_intangible_media_media_type'), table_name='intangible_media')
    op.drop_index(op.f('ix_intangible_media_intangible_id'), table_name='intangible_media')
    op.alter_column('intangible_media', 'media_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('intangible_media', 'sort_order')
    op.drop_column('intangible_media', 'processed_at')
    op.drop_column('intangible_media', 'created_at')
    op.drop_column('intangible_media', 'processing_status')
    op.drop_column('intangible_media', 'uploaded_by')
    op.drop_column('intangible_media', 'thumbnail_url')
    op.drop_column('intangible_media', 'height')
    op.drop_column('intangible_media', 'width')
    op.drop_column('intangible_media', 'mime_type')
    op.drop_column('intangible_media', 'file_size_mb')
    op.add_column('intangible_heritage', sa.Column('contribution_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('intangible_heritage', sa.Column('practiced_at', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('intangible_heritage', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('intangible_heritage', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('intangible_heritage', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'intangible_heritage', type_='foreignkey')
    op.drop_constraint(None, 'intangible_heritage', type_='foreignkey')
    op.drop_constraint(None, 'intangible_heritage', type_='foreignkey')
    op.create_foreign_key(op.f('intangible_heritage_location_id_fkey'), 'intangible_heritage', 'heritage_sites', ['location_id'], ['id'])
    op.create_foreign_key(op.f('intangible_heritage_contribution_id_fkey'), 'intangible_heritage', 'contributions', ['contribution_id'], ['id'])
    op.drop_index(op.f('ix_intangible_heritage_view_count'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_status'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_risk_level'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_location_id'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_created_at'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_contributor_id'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_community'), table_name='intangible_heritage')
    op.drop_index(op.f('ix_intangible_heritage_category'), table_name='intangible_heritage')
    op.alter_column('intangible_heritage', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('intangible_heritage', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('intangible_heritage', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('intangible_heritage', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('intangible_heritage', 'deleted_at')
    op.drop_column('intangible_heritage', 'engagement_score')
    op.drop_column('intangible_heritage', 'favorite_count')
    op.drop_column('intangible_heritage', 'view_count')
    op.drop_column('intangible_heritage', 'approved_at')
    op.drop_column('intangible_heritage', 'updated_at')
    op.drop_column('intangible_heritage', 'rejected_reason')
    op.drop_column('intangible_heritage', 'approval_notes')
    op.drop_column('intangible_heritage', 'approved_by')
    op.drop_column('intangible_heritage', 'contributor_id')
    op.drop_column('intangible_heritage', 'practiced_at_description')
    op.drop_column('intangible_heritage', 'name_en')
    op.drop_column('intangible_heritage', 'name_np')
    op.drop_index(op.f('ix_intangible_flags_status'), table_name='intangible_flags')
    op.drop_index(op.f('ix_intangible_flags_intangible_id'), table_name='intangible_flags')
    op.drop_index(op.f('ix_intangible_flags_id'), table_name='intangible_flags')
    op.drop_index(op.f('ix_intangible_flags_flagged_by'), table_name='intangible_flags')
    op.drop_index(op.f('ix_intangible_flags_flag_reason'), table_name='intangible_flags')
    op.drop_table('intangible_flags')
    op.drop_index(op.f('ix_intangible_engagement_user_id'), table_name='intangible_engagement')
    op.drop_index(op.f('ix_intangible_engagement_intangible_id'), table_name='intangible_engagement')
    op.drop_index(op.f('ix_intangible_engagement_id'), table_name='intangible_engagement')
    op.drop_index(op.f('ix_intangible_engagement_created_at'), table_name='intangible_engagement')
    op.drop_index(op.f('ix_intangible_engagement_action_type'), table_name='intangible_engagement')
    op.drop_table('intangible_engagement')
    op.drop_index(op.f('ix_intangible_comments_user_id'), table_name='intangible_comments')
    op.drop_index(op.f('ix_intangible_comments_parent_comment_id'), table_name='intangible_comments')
    op.drop_index(op.f('ix_intangible_comments_intangible_id'), table_name='intangible_comments')
    op.drop_index(op.f('ix_intangible_comments_id'), table_name='intangible_comments')
    op.drop_index(op.f('ix_intangible_comments_created_at'), table_name='intangible_comments')
    op.drop_table('intangible_comments')
    op.drop_index(op.f('ix_intangible_analytics_intangible_id'), table_name='intangible_analytics')
    op.drop_index(op.f('ix_intangible_analytics_id'), table_name='intangible_analytics')
    op.drop_index(op.f('ix_intangible_analytics_date'), table_name='intangible_analytics')
    op.drop_table('intangible_analytics')
    # ### end Alembic commands ###
