"""create heritage_sites table

Revision ID: 941f7497ff7f
Revises: dfeef8b68baf
Create Date: 2025-07-26 15:54:32.255394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '941f7497ff7f'
down_revision: Union[str, Sequence[str], None] = 'dfeef8b68baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('secondary_images', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heritage_sites_id'), 'heritage_sites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heritage_sites_id'), table_name='heritage_sites')
    op.drop_table('heritage_sites')
    # ### end Alembic commands ###
