"""Add recommendation models

Revision ID: 9ded3ca8acdc
Revises: 202606071200
Create Date: 2026-07-08 20:26:00.674437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ded3ca8acdc'
down_revision: Union[str, Sequence[str], None] = '202606071200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_history_id'), 'recommendation_history', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_history_user_id'), 'recommendation_history', ['user_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('site', 'festival', 'intangible', name='itemtype'), nullable=False),
    sa.Column('action_type', sa.Enum('view', 'bookmark', 'favorite', 'review', 'share', 'search', name='actiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_item_id'), 'user_activity', ['item_id'], unique=False)
    op.create_index('ix_user_activity_user_action', 'user_activity', ['user_id', 'action_type'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index('ix_user_activity_user_item', 'user_activity', ['user_id', 'item_id'], unique=False)
    op.create_table('user_interest_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tag_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interest_profile_id'), 'user_interest_profile', ['id'], unique=False)
    op.create_index(op.f('ix_user_interest_profile_user_id'), 'user_interest_profile', ['user_id'], unique=True)
    op.alter_column('festivals', 'is_location_specific',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('intangible_heritage', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intangible_heritage', 'tags')
    op.alter_column('festivals', 'is_location_specific',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_user_interest_profile_user_id'), table_name='user_interest_profile')
    op.drop_index(op.f('ix_user_interest_profile_id'), table_name='user_interest_profile')
    op.drop_table('user_interest_profile')
    op.drop_index('ix_user_activity_user_item', table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index('ix_user_activity_user_action', table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_item_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_recommendation_history_user_id'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_id'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    # ### end Alembic commands ###
