"""Add StoryReaction

Revision ID: c219eb98d228
Revises: 18d27b34ee8d
Create Date: 2026-05-30 20:24:51.649022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c219eb98d228'
down_revision: Union[str, Sequence[str], None] = '18d27b34ee8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['festival_stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_email', name='unique_story_user_reaction')
    )
    op.create_index(op.f('ix_story_reactions_id'), 'story_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_story_reactions_story_id'), 'story_reactions', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_reactions_user_email'), 'story_reactions', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_reactions_user_email'), table_name='story_reactions')
    op.drop_index(op.f('ix_story_reactions_story_id'), table_name='story_reactions')
    op.drop_index(op.f('ix_story_reactions_id'), table_name='story_reactions')
    op.drop_table('story_reactions')
    # ### end Alembic commands ###
