"""Add FestivalReminder and date determination type

Revision ID: d87effd531df
Revises: 869806b07071
Create Date: 2026-05-29 21:06:54.932765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd87effd531df'
down_revision: Union[str, Sequence[str], None] = '869806b07071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('festival_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('reminder_dates', postgresql.ARRAY(sa.DateTime(timezone=True)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_reminders_festival_id'), 'festival_reminders', ['festival_id'], unique=False)
    op.create_index(op.f('ix_festival_reminders_id'), 'festival_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_festival_reminders_user_email'), 'festival_reminders', ['user_email'], unique=False)
    datedeterminationtype = postgresql.ENUM('fixed_gregorian', 'api_synced_lunar', 'crowdsourced_variable', name='datedeterminationtype')
    datedeterminationtype.create(op.get_bind(), checkfirst=True)
    op.add_column('festivals', sa.Column('date_determination', datedeterminationtype, nullable=True))
    op.add_column('festivals', sa.Column('last_verified_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('festivals', 'last_verified_year')
    op.drop_column('festivals', 'date_determination')
    op.drop_index(op.f('ix_festival_reminders_user_email'), table_name='festival_reminders')
    op.drop_index(op.f('ix_festival_reminders_id'), table_name='festival_reminders')
    op.drop_index(op.f('ix_festival_reminders_festival_id'), table_name='festival_reminders')
    op.drop_table('festival_reminders')
    # ### end Alembic commands ###
