"""add moderation_note to festivals

Revision ID: f5b0c815b607
Revises: faabebd8f81e
Create Date: 2026-03-09 19:37:39.969662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b0c815b607'
down_revision: Union[str, Sequence[str], None] = 'faabebd8f81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('festivals', sa.Column('moderation_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('festivals', 'moderation_note')
    # ### end Alembic commands ###
