"""add_festival_tables

Revision ID: fd7aa6314581
Revises: 934c48886e84
Create Date: 2026-01-21 13:46:19.186040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd7aa6314581'
down_revision: Union[str, Sequence[str], None] = '934c48886e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'completed', 'cancelled', name='festivalstatus'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('secondary_images', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('ticket_info', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festivals_id'), 'festivals', ['id'], unique=False)
    op.create_table('festival_heritage_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('festival_id', sa.UUID(), nullable=False),
    sa.Column('heritage_site_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ),
    sa.ForeignKeyConstraint(['heritage_site_id'], ['heritage_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_heritage_sites_id'), 'festival_heritage_sites', ['id'], unique=False)
    op.add_column('contributions', sa.Column('festival_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contributions', 'festivals', ['festival_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_column('contributions', 'festival_id')
    op.drop_index(op.f('ix_festival_heritage_sites_id'), table_name='festival_heritage_sites')
    op.drop_table('festival_heritage_sites')
    op.drop_index(op.f('ix_festivals_id'), table_name='festivals')
    op.drop_table('festivals')
    # ### end Alembic commands ###
